package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	// Fields

	private Integer goodsId;

	private String goodsName;

	private String goodsMiaoshu;

	private String goodsPic;

	private String goodsYanse;

	private Integer goodsShichangjia;

	private Integer goodsTejia;

	private String goodsIsnottejia;

	private String goodsIsnottuijian;

	private Integer goodsCatelogId;
	private Integer goodsPinpaiId;
	private int goodsKucun;
	
	private String goodsDel;
	
	private String goodsCatelogName;//
	private String goodsPinpaiName;//
	
	private String chubanshe;
	private String zuozhe;
	private String bianhao;
	private Integer uid;
	private String shenhe;
	// Constructors

	/** default constructor */
	public TGoods()
	{
	}

	/** full constructor */
	public TGoods(String goodsName, String goodsMiaoshu, String goodsPic,
			String goodsYanse, Integer goodsShichangjia, Integer goodsTejia,
			String goodsIsnottejia, String goodsIsnottuijian,
			Integer goodsCatelogId)
	{
		this.goodsName = goodsName;
		this.goodsMiaoshu = goodsMiaoshu;
		this.goodsPic = goodsPic;
		this.goodsYanse = goodsYanse;
		this.goodsShichangjia = goodsShichangjia;
		this.goodsTejia = goodsTejia;
		this.goodsIsnottejia = goodsIsnottejia;
		this.goodsIsnottuijian = goodsIsnottuijian;
		this.goodsCatelogId = goodsCatelogId;
	}

	// Property accessors

	public Integer getGoodsPinpaiId() {
		return goodsPinpaiId;
	}

	public void setGoodsPinpaiId(Integer goodsPinpaiId) {
		this.goodsPinpaiId = goodsPinpaiId;
	}

	public String getGoodsPinpaiName() {
		return goodsPinpaiName;
	}

	public void setGoodsPinpaiName(String goodsPinpaiName) {
		this.goodsPinpaiName = goodsPinpaiName;
	}

	public Integer getGoodsId()
	{
		return this.goodsId;
	}

	public String getGoodsDel()
	{
		return goodsDel;
	}

	public int getGoodsKucun()
	{
		return goodsKucun;
	}

	public void setGoodsKucun(int goodsKucun)
	{
		this.goodsKucun = goodsKucun;
	}

	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}

	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}

	public String getGoodsName()
	{
		return this.goodsName;
	}

	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}

	public String getGoodsMiaoshu()
	{
		return this.goodsMiaoshu;
	}

	public void setGoodsMiaoshu(String goodsMiaoshu)
	{
		this.goodsMiaoshu = goodsMiaoshu;
	}

	public String getGoodsPic()
	{
		return this.goodsPic;
	}

	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}

	public String getGoodsYanse()
	{
		return this.goodsYanse;
	}

	public void setGoodsYanse(String goodsYanse)
	{
		this.goodsYanse = goodsYanse;
	}

	public Integer getGoodsShichangjia()
	{
		return this.goodsShichangjia;
	}

	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}

	public Integer getGoodsTejia()
	{
		return this.goodsTejia;
	}

	public void setGoodsTejia(Integer goodsTejia)
	{
		this.goodsTejia = goodsTejia;
	}

	public String getGoodsIsnottejia()
	{
		return this.goodsIsnottejia;
	}

	public void setGoodsIsnottejia(String goodsIsnottejia)
	{
		this.goodsIsnottejia = goodsIsnottejia;
	}

	public String getGoodsIsnottuijian()
	{
		return this.goodsIsnottuijian;
	}

	public void setGoodsIsnottuijian(String goodsIsnottuijian)
	{
		this.goodsIsnottuijian = goodsIsnottuijian;
	}

	public Integer getGoodsCatelogId()
	{
		return this.goodsCatelogId;
	}

	public void setGoodsCatelogId(Integer goodsCatelogId)
	{
		this.goodsCatelogId = goodsCatelogId;
	}

	public String getGoodsCatelogName()
	{
		return goodsCatelogName;
	}

	public void setGoodsCatelogName(String goodsCatelogName)
	{
		this.goodsCatelogName = goodsCatelogName;
	}

	public String getChubanshe() {
		return chubanshe;
	}

	public void setChubanshe(String chubanshe) {
		this.chubanshe = chubanshe;
	}

	public String getZuozhe() {
		return zuozhe;
	}

	public void setZuozhe(String zuozhe) {
		this.zuozhe = zuozhe;
	}

	public String getBianhao() {
		return bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	
	
	
	public String getShenhe() {
		return shenhe;
	}

	public void setShenhe(String shenhe) {
		this.shenhe = shenhe;
	}

	@Override
	public String toString() {
		return "TGoods [goodsId=" + goodsId + ", goodsName=" + goodsName
				+ ", goodsMiaoshu=" + goodsMiaoshu + ", goodsPic=" + goodsPic
				+ ", goodsYanse=" + goodsYanse + ", goodsShichangjia="
				+ goodsShichangjia + ", goodsTejia=" + goodsTejia
				+ ", goodsIsnottejia=" + goodsIsnottejia
				+ ", goodsIsnottuijian=" + goodsIsnottuijian
				+ ", goodsCatelogId=" + goodsCatelogId + ", goodsKucun="
				+ goodsKucun + ", goodsDel=" + goodsDel + ", goodsCatelogName="
				+ goodsCatelogName + "]";
	}

}