package com.model;

/**
 * TPinpai generated by MyEclipse Persistence Tools
 */

public class TPinpai implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String miaoshu;
	
	private String del;

	// Constructors

	/** default constructor */
	public TPinpai()
	{
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMiaoshu() {
		return miaoshu;
	}

	public void setMiaoshu(String miaoshu) {
		this.miaoshu = miaoshu;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}


}